[default]
extend-ignore-identifiers-re = ["Fo"]

[files]
# TODO(danbugs): update this when I'm done w/ the move
extend-exclude = ["**/*.patch", "src/hyperlight_guest/third_party/**/*", "NOTICE.txt"]

[default.extend-words]
# typ is used for field name as type is a reserved keyword
typ="typ"
